/**
 * MONOLITH MCP catalog — external tool servers this engine can actually reach.
 *
 * Classified against the engine's real contract, not a vendor list: the MCP
 * client speaks **stdio** and **streamable-http** only, authenticates with
 * static headers only, and bridges **tools** (never resources or prompts).
 * Entries that a different client could reach but this one cannot are kept
 * with `status: 'unsupported'` and the reason, so nobody re-discovers the
 * limitation by debugging a silent connect.
 *
 * Package names were checked against npm and PyPI on 2026-09-04;
 * `registry: 'verified'` means the name resolved that day.
 *
 * An `{ expr }` value is emitted into the generated patch as a `!!js`
 * expression rather than a quoted string — that is how a row reads a secret
 * from the environment instead of baking it into a committed file.
 * @module
 */

/** @typedef {'stdio'|'streamable-http'|'builtin'} McpTransport */
/** @typedef {'ready'|'needs-secret'|'built-in'|'unsupported'} McpStatus */

/** Every catalogued server, in category order. */
export const CATALOG = [
  {"id":"monolith-web","name":"Web Search & Fetch","category":"web","description":"Built-in web search (SearXNG or DuckDuckGo) and URL reader. Always on.","transport":"builtin","status":"built-in","secrets":[]},
  {"id":"ms-365","name":"Microsoft 365 (Teams, Outlook, OneDrive)","category":"office","description":"Teams chats, Outlook mail & calendar, OneDrive, Excel, To Do and more via Microsoft Graph. Sign in with a device code on first use.","docsUrl":"https://github.com/softeria/ms-365-mcp-server","notes":"Community server. Device-code sign-in on first use.","transport":"stdio","command":"npx","args":["-y","@softeria/ms-365-mcp-server"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"word","name":"Word Documents","category":"office","description":"Create and edit .docx files: text, headings, tables, images, formatting.","docsUrl":"https://github.com/GongRzhe/Office-Word-MCP-Server","notes":"Requires uv (Python).","transport":"stdio","command":"uvx","args":["office-word-mcp-server"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"powerpoint","name":"PowerPoint Presentations","category":"office","description":"Create and edit .pptx decks: slides, layouts, charts, images, speaker notes.","docsUrl":"https://github.com/GongRzhe/Office-PowerPoint-MCP-Server","notes":"Requires uv (Python).","transport":"stdio","command":"uvx","args":["office-powerpoint-mcp-server"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"excel","name":"Excel Workbooks","category":"office","description":"Read and write .xlsx workbooks: sheets, cells, formulas, tables.","docsUrl":"https://github.com/negokaz/excel-mcp-server","transport":"stdio","command":"npx","args":["-y","@negokaz/excel-mcp-server"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"google-calendar","name":"Google Calendar","category":"office","description":"List, search, create and update calendar events.","docsUrl":"https://github.com/nspady/google-calendar-mcp","notes":"Needs a Google Cloud OAuth credentials JSON file.","transport":"stdio","command":"npx","args":["-y","@cocal/google-calendar-mcp"],"env":{"GOOGLE_OAUTH_CREDENTIALS":{ expr: "process.env.GOOGLE_OAUTH_CREDENTIALS ?? ''" }},"secrets":[{"env":"GOOGLE_OAUTH_CREDENTIALS","label":"Path to OAuth credentials JSON","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"gmail","name":"Gmail","category":"office","description":"Read, search, send and label Gmail messages.","docsUrl":"https://github.com/GongRzhe/Gmail-MCP-Server","notes":"Community server. One-time OAuth setup (gcp-oauth.keys.json) per its README.","transport":"stdio","command":"npx","args":["-y","@gongrzhe/server-gmail-autoauth-mcp"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"email-imap","name":"Email (IMAP/SMTP — Zoho, Outlook, any)","category":"office","description":"Read and send mail on any IMAP/SMTP mailbox — works with Zoho Mail, Outlook, Gmail, and self-hosted mail.","docsUrl":"https://github.com/ai-zerolab/mcp-email-server","notes":"Requires uv (Python). Run 'uvx mcp-email-server@latest ui' once to configure accounts.","transport":"stdio","command":"uvx","args":["mcp-email-server@latest","stdio"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"google-drive","name":"Google Drive","category":"office","description":"Search and read files in Google Drive (Docs exported as text).","docsUrl":"https://github.com/modelcontextprotocol/servers-archived/tree/main/src/gdrive","notes":"Archived reference server. Needs a Google OAuth credentials JSON file.","transport":"stdio","command":"npx","args":["-y","@modelcontextprotocol/server-gdrive"],"env":{"GDRIVE_CREDENTIALS_PATH":{ expr: "process.env.GDRIVE_CREDENTIALS_PATH ?? ''" }},"secrets":[{"env":"GDRIVE_CREDENTIALS_PATH","label":"Path to OAuth credentials JSON","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"google-sheets","name":"Google Sheets","category":"office","description":"Read, write and format Google Sheets spreadsheets.","docsUrl":"https://github.com/xing5/mcp-google-sheets","notes":"Requires uv (Python) and a Google service-account JSON.","transport":"stdio","command":"uvx","args":["mcp-google-sheets@latest"],"env":{"SERVICE_ACCOUNT_PATH":{ expr: "process.env.SERVICE_ACCOUNT_PATH ?? ''" },"DRIVE_FOLDER_ID":{ expr: "process.env.DRIVE_FOLDER_ID ?? ''" }},"secrets":[{"env":"SERVICE_ACCOUNT_PATH","label":"Path to service-account JSON","required":true},{"env":"DRIVE_FOLDER_ID","label":"Drive folder ID (optional)","required":false}],"status":"needs-secret","registry":"verified"},
  {"id":"slack","name":"Slack","category":"communication","description":"Read channels and post messages in your Slack workspace.","docsUrl":"https://github.com/modelcontextprotocol/servers-archived/tree/main/src/slack","notes":"Archived reference server.","transport":"stdio","command":"npx","args":["-y","@modelcontextprotocol/server-slack"],"env":{"SLACK_BOT_TOKEN":{ expr: "process.env.SLACK_BOT_TOKEN ?? ''" },"SLACK_TEAM_ID":{ expr: "process.env.SLACK_TEAM_ID ?? ''" }},"secrets":[{"env":"SLACK_BOT_TOKEN","label":"Bot token (xoxb-…)","required":true},{"env":"SLACK_TEAM_ID","label":"Team ID (T…)","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"zapier","name":"Zapier (7000+ apps)","category":"communication","description":"Bridge to thousands of apps — Teams, Gmail, Sheets, CRMs, calendars — through your Zapier MCP endpoint.","docsUrl":"https://zapier.com/mcp","notes":"Create your personal MCP URL at zapier.com/mcp.","transport":"streamable-http","url":{ expr: "${process.env.ZAPIER_MCP_URL}" },"secrets":[{"env":"ZAPIER_MCP_URL","label":"Your Zapier MCP server URL","required":true}],"status":"needs-secret"},
  {"id":"linear","name":"Linear","category":"productivity","description":"Issues, projects and cycles in Linear.","docsUrl":"https://linear.app/docs/mcp","notes":"Official remote server. OAuth sign-in on first connect.","transport":"streamable-http","url":"https://mcp.linear.app/mcp","secrets":[],"status":"unsupported","blocked":"oauth"},
  {"id":"atlassian","name":"Jira & Confluence","category":"productivity","description":"Search and update Jira issues; read and write Confluence pages.","docsUrl":"https://github.com/sooperset/mcp-atlassian","notes":"Requires uv (Python). Use an Atlassian API token.","transport":"stdio","command":"uvx","args":["mcp-atlassian"],"env":{"JIRA_URL":{ expr: "process.env.JIRA_URL ?? ''" },"JIRA_USERNAME":{ expr: "process.env.JIRA_USERNAME ?? ''" },"JIRA_API_TOKEN":{ expr: "process.env.JIRA_API_TOKEN ?? ''" },"CONFLUENCE_URL":{ expr: "process.env.CONFLUENCE_URL ?? ''" },"CONFLUENCE_USERNAME":{ expr: "process.env.CONFLUENCE_USERNAME ?? ''" },"CONFLUENCE_API_TOKEN":{ expr: "process.env.CONFLUENCE_API_TOKEN ?? ''" }},"secrets":[{"env":"JIRA_URL","label":"Jira URL (https://you.atlassian.net)","required":true},{"env":"JIRA_USERNAME","label":"Account email","required":true},{"env":"JIRA_API_TOKEN","label":"API token","required":true},{"env":"CONFLUENCE_URL","label":"Confluence URL (optional)","required":false},{"env":"CONFLUENCE_USERNAME","label":"Account email","required":true},{"env":"CONFLUENCE_API_TOKEN","label":"API token","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"asana","name":"Asana","category":"productivity","description":"Tasks, projects and goals in Asana.","docsUrl":"https://developers.asana.com/docs/mcp-server","notes":"Official remote server. OAuth sign-in on first connect.","transport":"streamable-http","url":"https://mcp.asana.com/sse","secrets":[],"status":"unsupported","blocked":"sse"},
  {"id":"todoist","name":"Todoist","category":"productivity","description":"Create, complete and organize Todoist tasks in natural language.","docsUrl":"https://github.com/abhiz123/todoist-mcp-server","transport":"stdio","command":"npx","args":["-y","@abhiz123/todoist-mcp-server"],"env":{"TODOIST_API_TOKEN":{ expr: "process.env.TODOIST_API_TOKEN ?? ''" }},"secrets":[{"env":"TODOIST_API_TOKEN","label":"API token","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"notion","name":"Notion","category":"productivity","description":"Read and search your Notion pages and databases from the agent.","docsUrl":"https://github.com/makenotion/notion-mcp-server","transport":"stdio","command":"npx","args":["-y","@notionhq/notion-mcp-server"],"env":{"NOTION_TOKEN":{ expr: "process.env.NOTION_TOKEN ?? ''" }},"secrets":[{"env":"NOTION_TOKEN","label":"Internal integration token","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"airtable","name":"Airtable","category":"productivity","description":"Read and write Airtable bases, tables and records.","docsUrl":"https://github.com/domdomegg/airtable-mcp-server","transport":"stdio","command":"npx","args":["-y","airtable-mcp-server"],"env":{"AIRTABLE_API_KEY":{ expr: "process.env.AIRTABLE_API_KEY ?? ''" }},"secrets":[{"env":"AIRTABLE_API_KEY","label":"Personal access token","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"obsidian","name":"Obsidian Vault","category":"productivity","description":"Read and search the Markdown notes in an Obsidian vault directory.","docsUrl":"https://github.com/smithery-ai/mcp-obsidian","transport":"stdio","command":"npx","args":["-y","mcp-obsidian","{vaultPath}"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"github","name":"GitHub","category":"development","description":"Repos, pull requests, issues, and code search on GitHub — no local clone needed.","docsUrl":"https://github.com/github/github-mcp-server","transport":"streamable-http","url":"https://api.githubcopilot.com/mcp/","headers":{"Authorization":{ expr: "Bearer ${process.env.GITHUB_TOKEN}" }},"secrets":[{"env":"GITHUB_TOKEN","label":"Personal access token","required":true}],"status":"needs-secret"},
  {"id":"gitlab","name":"GitLab","category":"development","description":"Projects, merge requests, issues and pipelines on GitLab.","docsUrl":"https://github.com/zereight/gitlab-mcp","notes":"Community server.","transport":"stdio","command":"npx","args":["-y","@zereight/mcp-gitlab"],"env":{"GITLAB_PERSONAL_ACCESS_TOKEN":{ expr: "process.env.GITLAB_PERSONAL_ACCESS_TOKEN ?? ''" },"GITLAB_API_URL":{ expr: "process.env.GITLAB_API_URL ?? ''" }},"secrets":[{"env":"GITLAB_PERSONAL_ACCESS_TOKEN","label":"Personal access token","required":true},{"env":"GITLAB_API_URL","label":"API URL (optional, for self-hosted)","required":false}],"status":"needs-secret","registry":"verified"},
  {"id":"postman","name":"Postman","category":"development","description":"Manage Postman collections, environments and run API requests.","docsUrl":"https://github.com/postmanlabs/postman-mcp-server","transport":"stdio","command":"npx","args":["-y","@postman/postman-mcp-server"],"env":{"POSTMAN_API_KEY":{ expr: "process.env.POSTMAN_API_KEY ?? ''" }},"secrets":[{"env":"POSTMAN_API_KEY","label":"Postman API key","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"sentry","name":"Sentry","category":"development","description":"Query errors, issues and performance data from Sentry.","docsUrl":"https://docs.sentry.io/product/sentry-mcp/","notes":"Official remote server. OAuth sign-in on first connect.","transport":"streamable-http","url":"https://mcp.sentry.dev/mcp","secrets":[],"status":"unsupported","blocked":"oauth"},
  {"id":"e2b","name":"Code Execution (E2B)","category":"development","description":"Run Python/JS in a secure cloud sandbox — data analysis, charts, file generation.","docsUrl":"https://github.com/e2b-dev/mcp-server","transport":"stdio","command":"npx","args":["-y","@e2b/mcp-server"],"env":{"E2B_API_KEY":{ expr: "process.env.E2B_API_KEY ?? ''" }},"secrets":[{"env":"E2B_API_KEY","label":"E2B API key","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"playwright","name":"Browser (Playwright)","category":"web","description":"Drive a real browser: open pages, click, type, screenshot — for testing and web automation.","docsUrl":"https://github.com/microsoft/playwright-mcp","transport":"stdio","command":"npx","args":["-y","@playwright/mcp@latest"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"context7","name":"Context7 Docs","category":"development","description":"Up-to-date library documentation and code examples for prompts (Upstash Context7).","docsUrl":"https://github.com/upstash/context7","transport":"streamable-http","url":"https://mcp.context7.com/mcp","headers":{"CONTEXT7_API_KEY":{ expr: "${process.env.CONTEXT7_API_KEY}" }},"secrets":[{"env":"CONTEXT7_API_KEY","label":"API key (optional — higher rate limits)","required":false}],"status":"needs-secret"},
  {"id":"figma","name":"Figma","category":"development","description":"Read Figma file structure, components and styles for design-to-code work.","docsUrl":"https://github.com/GLips/Figma-Context-MCP","notes":"Community server.","transport":"stdio","command":"npx","args":["-y","figma-developer-mcp","--stdio"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"kubernetes","name":"Kubernetes","category":"cloud","description":"Inspect and manage cluster resources using your local kubeconfig.","docsUrl":"https://github.com/Flux159/mcp-server-kubernetes","notes":"Uses your current kubectl context.","transport":"stdio","command":"npx","args":["-y","mcp-server-kubernetes"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"docker","name":"Docker","category":"cloud","description":"Manage containers, images, volumes and compose stacks on this machine.","docsUrl":"https://github.com/QuantGeekDev/docker-mcp","notes":"Requires uv (Python) and a running Docker daemon.","transport":"stdio","command":"uvx","args":["docker-mcp"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"aws-docs","name":"AWS Documentation","category":"cloud","description":"Search and read AWS documentation (official AWS Labs server).","docsUrl":"https://github.com/awslabs/mcp","notes":"Requires uv (Python).","transport":"stdio","command":"uvx","args":["awslabs.aws-documentation-mcp-server@latest"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"azure","name":"Azure","category":"cloud","description":"Query and manage Azure resources (official Microsoft server).","docsUrl":"https://github.com/Azure/azure-mcp","notes":"Uses your local 'az login' credentials.","transport":"stdio","command":"npx","args":["-y","@azure/mcp@latest","server","start"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"cloudflare-docs","name":"Cloudflare Docs","category":"cloud","description":"Search Cloudflare developer documentation (Workers, R2, KV, DNS). No account needed.","docsUrl":"https://github.com/cloudflare/mcp-server-cloudflare","transport":"streamable-http","url":"https://docs.mcp.cloudflare.com/sse","secrets":[],"status":"unsupported","blocked":"sse"},
  {"id":"vercel","name":"Vercel","category":"cloud","description":"Deployments, projects and logs on Vercel.","docsUrl":"https://vercel.com/docs/mcp/vercel-mcp","notes":"Official remote server. OAuth sign-in on first connect.","transport":"streamable-http","url":"https://mcp.vercel.com","secrets":[],"status":"unsupported","blocked":"oauth"},
  {"id":"netlify","name":"Netlify","category":"cloud","description":"Create, deploy and manage Netlify sites (official server).","docsUrl":"https://docs.netlify.com/build/build-with-ai/netlify-mcp-server/","transport":"stdio","command":"npx","args":["-y","@netlify/mcp"],"env":{"NETLIFY_PERSONAL_ACCESS_TOKEN":{ expr: "process.env.NETLIFY_PERSONAL_ACCESS_TOKEN ?? ''" }},"secrets":[{"env":"NETLIFY_PERSONAL_ACCESS_TOKEN","label":"Personal access token (optional if 'netlify login' done)","required":false}],"status":"ready","registry":"verified"},
  {"id":"heroku","name":"Heroku","category":"cloud","description":"Manage Heroku apps, dynos, add-ons and logs (official server).","docsUrl":"https://github.com/heroku/heroku-mcp-server","transport":"stdio","command":"npx","args":["-y","@heroku/mcp-server"],"env":{"HEROKU_API_KEY":{ expr: "process.env.HEROKU_API_KEY ?? ''" }},"secrets":[{"env":"HEROKU_API_KEY","label":"Heroku API key","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"supabase","name":"Supabase","category":"data","description":"Query your Supabase database, inspect schema, logs, and advisors. Seeded read-only for safety.","docsUrl":"https://supabase.com/docs/guides/getting-started/mcp","transport":"stdio","command":"npx","args":["-y","@supabase/mcp-server-supabase@latest","--read-only"],"env":{"SUPABASE_ACCESS_TOKEN":{ expr: "process.env.SUPABASE_ACCESS_TOKEN ?? ''" }},"secrets":[{"env":"SUPABASE_ACCESS_TOKEN","label":"Personal access token","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"postgres","name":"PostgreSQL","category":"data","description":"Read-only SQL queries and schema inspection against any Postgres database.","docsUrl":"https://github.com/modelcontextprotocol/servers-archived/tree/main/src/postgres","notes":"Archived reference server.","transport":"stdio","command":"npx","args":["-y","@modelcontextprotocol/server-postgres","{connectionString}"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"mysql","name":"MySQL","category":"data","description":"Query MySQL/MariaDB databases with schema inspection.","docsUrl":"https://github.com/benborla/mcp-server-mysql","notes":"Community server.","transport":"stdio","command":"npx","args":["-y","@benborla29/mcp-server-mysql"],"env":{"MYSQL_HOST":{ expr: "process.env.MYSQL_HOST ?? ''" },"MYSQL_PORT":{ expr: "process.env.MYSQL_PORT ?? ''" },"MYSQL_USER":{ expr: "process.env.MYSQL_USER ?? ''" },"MYSQL_PASS":{ expr: "process.env.MYSQL_PASS ?? ''" },"MYSQL_DB":{ expr: "process.env.MYSQL_DB ?? ''" }},"secrets":[{"env":"MYSQL_HOST","label":"Host","required":true},{"env":"MYSQL_PORT","label":"Port (optional, default 3306)","required":false},{"env":"MYSQL_USER","label":"User","required":true},{"env":"MYSQL_PASS","label":"Password","required":true},{"env":"MYSQL_DB","label":"Database","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"sqlite","name":"SQLite","category":"data","description":"Query and analyze a local SQLite database file.","docsUrl":"https://github.com/modelcontextprotocol/servers-archived/tree/main/src/sqlite","notes":"Requires uv (Python). Archived reference server.","transport":"stdio","command":"uvx","args":["mcp-server-sqlite","--db-path","{dbPath}"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"mongodb","name":"MongoDB","category":"data","description":"Query MongoDB collections and Atlas clusters (official server).","docsUrl":"https://github.com/mongodb-js/mongodb-mcp-server","transport":"stdio","command":"npx","args":["-y","mongodb-mcp-server"],"env":{"MDB_MCP_CONNECTION_STRING":{ expr: "process.env.MDB_MCP_CONNECTION_STRING ?? ''" }},"secrets":[{"env":"MDB_MCP_CONNECTION_STRING","label":"Connection string (mongodb+srv://…)","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"redis","name":"Redis","category":"data","description":"Inspect keys and run commands against a Redis instance.","docsUrl":"https://github.com/modelcontextprotocol/servers-archived/tree/main/src/redis","notes":"Archived reference server.","transport":"stdio","command":"npx","args":["-y","@modelcontextprotocol/server-redis","{redisUrl}"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"neon","name":"Neon Postgres","category":"data","description":"Manage Neon serverless Postgres: projects, branches, SQL (official server).","docsUrl":"https://neon.com/docs/ai/neon-mcp-server","transport":"stdio","command":"npx","args":["-y","@neondatabase/mcp-server-neon","start","{apiKey}"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"stripe","name":"Stripe","category":"business","description":"Query Stripe customers, payments, and invoices. Use a restricted (read-only) key.","docsUrl":"https://docs.stripe.com/mcp","transport":"stdio","command":"npx","args":["-y","@stripe/mcp","--tools=all","--api-key={apiKey}"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"paypal","name":"PayPal","category":"business","description":"Invoices, payments and disputes through PayPal's official MCP.","docsUrl":"https://developer.paypal.com/tools/mcp-server/","notes":"Official remote server. OAuth sign-in on first connect.","transport":"streamable-http","url":"https://mcp.paypal.com/sse","secrets":[],"status":"unsupported","blocked":"sse"},
  {"id":"hubspot","name":"HubSpot","category":"business","description":"CRM contacts, companies and deals (official HubSpot server).","docsUrl":"https://developers.hubspot.com/mcp","transport":"stdio","command":"npx","args":["-y","@hubspot/mcp-server"],"env":{"PRIVATE_APP_ACCESS_TOKEN":{ expr: "process.env.PRIVATE_APP_ACCESS_TOKEN ?? ''" }},"secrets":[{"env":"PRIVATE_APP_ACCESS_TOKEN","label":"Private app access token","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"shopify-dev","name":"Shopify Dev","category":"business","description":"Search Shopify developer docs and Admin API schemas (official server, no account needed).","docsUrl":"https://shopify.dev/docs/apps/build/devmcp","transport":"stdio","command":"npx","args":["-y","@shopify/dev-mcp@latest"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"brave-search","name":"Brave Search","category":"research","description":"Web search through the Brave Search API — stabler than scraping, generous free tier.","docsUrl":"https://brave.com/search/api/","transport":"stdio","command":"npx","args":["-y","@modelcontextprotocol/server-brave-search"],"env":{"BRAVE_API_KEY":{ expr: "process.env.BRAVE_API_KEY ?? ''" }},"secrets":[{"env":"BRAVE_API_KEY","label":"Brave Search API key","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"tavily","name":"Tavily Search","category":"research","description":"AI-optimized web search and content extraction with cited results.","docsUrl":"https://github.com/tavily-ai/tavily-mcp","transport":"stdio","command":"npx","args":["-y","tavily-mcp"],"env":{"TAVILY_API_KEY":{ expr: "process.env.TAVILY_API_KEY ?? ''" }},"secrets":[{"env":"TAVILY_API_KEY","label":"Tavily API key","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"exa","name":"Exa Search","category":"research","description":"Semantic web search built for AI: papers, companies, code, news.","docsUrl":"https://github.com/exa-labs/exa-mcp-server","transport":"stdio","command":"npx","args":["-y","exa-mcp-server"],"env":{"EXA_API_KEY":{ expr: "process.env.EXA_API_KEY ?? ''" }},"secrets":[{"env":"EXA_API_KEY","label":"Exa API key","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"perplexity","name":"Perplexity","category":"research","description":"Ask Perplexity's Sonar models for researched, cited answers.","docsUrl":"https://github.com/ppl-ai/modelcontextprotocol","transport":"stdio","command":"npx","args":["-y","server-perplexity-ask"],"env":{"PERPLEXITY_API_KEY":{ expr: "process.env.PERPLEXITY_API_KEY ?? ''" }},"secrets":[{"env":"PERPLEXITY_API_KEY","label":"Perplexity API key","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"firecrawl","name":"Firecrawl","category":"research","description":"Powerful web scraping and crawling: clean markdown from any site, whole-site crawls.","docsUrl":"https://docs.firecrawl.dev/mcp","transport":"stdio","command":"npx","args":["-y","firecrawl-mcp"],"env":{"FIRECRAWL_API_KEY":{ expr: "process.env.FIRECRAWL_API_KEY ?? ''" }},"secrets":[{"env":"FIRECRAWL_API_KEY","label":"Firecrawl API key","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"arxiv","name":"arXiv Papers","category":"research","description":"Search, download and read academic papers from arXiv.","docsUrl":"https://github.com/blazickjp/arxiv-mcp-server","notes":"Requires uv (Python).","transport":"stdio","command":"uvx","args":["arxiv-mcp-server"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"youtube-transcript","name":"YouTube Transcripts","category":"research","description":"Fetch transcripts/subtitles for YouTube videos for summarizing.","docsUrl":"https://github.com/kimtaeyoon83/mcp-server-youtube-transcript","transport":"stdio","command":"npx","args":["-y","@kimtaeyoon83/mcp-server-youtube-transcript"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"hackernews","name":"Hacker News","category":"research","description":"Browse Hacker News stories and comments.","docsUrl":"https://github.com/erithwik/mcp-hn","notes":"Requires uv (Python).","transport":"stdio","command":"uvx","args":["mcp-hn"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"google-maps","name":"Google Maps","category":"research","description":"Geocoding, place search, directions and distances.","docsUrl":"https://github.com/modelcontextprotocol/servers-archived/tree/main/src/google-maps","notes":"Archived reference server.","transport":"stdio","command":"npx","args":["-y","@modelcontextprotocol/server-google-maps"],"env":{"GOOGLE_MAPS_API_KEY":{ expr: "process.env.GOOGLE_MAPS_API_KEY ?? ''" }},"secrets":[{"env":"GOOGLE_MAPS_API_KEY","label":"Google Maps API key","required":true}],"status":"needs-secret","registry":"verified"},
  {"id":"memory","name":"Memory (Knowledge Graph)","category":"utilities","description":"Persistent knowledge-graph memory the agent can read and write across sessions.","docsUrl":"https://github.com/modelcontextprotocol/servers/tree/main/src/memory","transport":"stdio","command":"npx","args":["-y","@modelcontextprotocol/server-memory"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"sequential-thinking","name":"Sequential Thinking","category":"utilities","description":"Structured step-by-step reasoning tool for complex problem decomposition.","docsUrl":"https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking","transport":"stdio","command":"npx","args":["-y","@modelcontextprotocol/server-sequential-thinking"],"secrets":[],"status":"ready","registry":"corrected"},
  {"id":"time","name":"Time & Timezones","category":"utilities","description":"Current time and timezone conversions (official reference server).","docsUrl":"https://github.com/modelcontextprotocol/servers/tree/main/src/time","notes":"Requires uv (Python).","transport":"stdio","command":"uvx","args":["mcp-server-time"],"secrets":[],"status":"ready","registry":"verified"},
  {"id":"elevenlabs","name":"ElevenLabs (Text-to-Speech)","category":"utilities","description":"Generate speech audio and voice clones from text (official server).","docsUrl":"https://github.com/elevenlabs/elevenlabs-mcp","notes":"Requires uv (Python).","transport":"stdio","command":"uvx","args":["elevenlabs-mcp"],"env":{"ELEVENLABS_API_KEY":{ expr: "process.env.ELEVENLABS_API_KEY ?? ''" }},"secrets":[{"env":"ELEVENLABS_API_KEY","label":"ElevenLabs API key","required":true}],"status":"needs-secret","registry":"verified"},
]

/** Servers that connect with no credential at all. */
export const READY = CATALOG.filter(e => e.status === 'ready')

/** Servers that connect once their environment variables are set. */
export const NEEDS_SECRET = CATALOG.filter(e => e.status === 'needs-secret')

/** Servers this engine cannot reach, each carrying `blocked` with the reason. */
export const UNSUPPORTED = CATALOG.filter(e => e.status === 'unsupported')
